# Generated by Django 4.0.8 on 2022-11-29 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ViewStudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
