# Generated by Django 4.0.8 on 2022-12-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewStudy', '0003_author_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
